export enum Route {
  Auth = 'auth',
  User = 'user',
  Register = 'register',
  Login = 'login',
  Tasks = 'tasks',
  Task = 'task',
  MyTasks = 'my-tasks',
  NewTasks = 'new',
  Comments = 'comments',
  Categories = 'categories',
  TasksNotify = 'tasks-notify',
  Executer = 'executer',
  Reaction = 'reaction',
  Reactions = 'reactions',
  ChangeStatus = 'change-status',
  Cancel = 'cancel',
  Static = 'static',
  Assets = 'assets',
  RefreshToken = 'refresh',
  UploadAvatar = 'upload-avatar',
  UploadImage = 'upload-image',
  Review = 'review',
  ChangePassword = 'change-password',
  AddSubscriberTemlate = './add-subscriber',
  NewTasksTemplate = './new-tasks',
}
