# Create a new comment
POST http://localhost:3335/api/comments HTTP/1.1
Content-Type: application/json
User-Id: 123 

{
  "text": "класс, всё очень круто",
  "taskId": "c18ff9ef-7951-427f-a0cf-1b824360b2ab"
}

###

# Get comments 
GET http://localhost:3335/api/comments/task/c18ff9ef-7951-427f-a0cf-1b824360b2ab?limit=50&page=2 HTTP/1.1

###

# Delete comment
DELETE  http://localhost:3335/api/comments/201ca431-4e94-44b1-acb5-066ca929036f HTTP/1.1


###