# Create a new user
POST http://localhost:3334/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "email": "user@notfound2.local",
  "dateBirth": "2005-01-15",
  "username": "Иван Иванов",
  "password": "123456",
  "role": "Заказчик",
  "city": "Москва"
}

###

# Login user by email and password
POST http://localhost:3334/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "user@notfound1.local",
  "password": "123456"
}

###

# Refresh tokens
GET http://localhost:3334/api/auth/refresh HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2Mzk4YzhiMmU2Njg2YTRhODgwZjUzYzEiLCJlbWFpbCI6InVzZXJAbm90Zm91bmQxLmxvY2FsIiwicm9sZSI6ItCX0LDQutCw0LfRh9C40LoiLCJsYXN0bmFtZSI6IlNtaXRoIiwiZmlyc3RuYW1lIjoic3NzcyIsImlhdCI6MTY3MDk2MTIyMywiZXhwIjoxNjcwOTYzMjIzfQ._KC8ldcgBsDNVg5vRhw1Ygu3mgEyR8pJg14Xe-C4p2I

###

# Upload Avatar
POST http://localhost:3334/api/auth/upload-avatar
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2M1OWU5ZWYwYmE3MGJiYjA0ZjNjMTMiLCJlbWFpbCI6InVzZXJAbm90Zm91bmQxLmxvY2FsIiwicm9sZSI6ItCX0LDQutCw0LfRh9C40LoiLCJsYXN0bmFtZSI6ItCY0LLQsNC90L7QsiIsImZpcnN0bmFtZSI6ItCY0LLQsNC9IiwiaWF0IjoxNjczODk1NTg1LCJleHAiOjE2NzM4OTc1ODV9.kXOa0vCm1pgMY3vXi9xN-VBCjjp4zqDbqNQJckC8g4I
Content-Type: multipart/form-data; boundary=Upload

--Upload
Content-Disposition: form-data; name="file"; filename="1.png"
Content-Type: image/png

< ../../../../../../markup/img/avatars/2.png
--Upload--

###

# download avatar
GET http://localhost:3334/static/52438ebb-7774-4aac-82f3-03928166cb9e.png HTTP/1.1

###